/* eslint-disable no-unused-vars */
const TRIP = {
  meta: {
    title: "המדריך המשפחתי שלנו",
    shareTitle: "המדריך המשפחתי שלנו לאוסטריה 🏔️",
    shareUrl: "https://estyca-tr.github.io/austria-family-guide/",
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=85",
    gallery: [
      { title: "הלשטאט", image: PLACES.hallstatt.image, url: PLACES.hallstatt.web },
      { title: "קרחון דכשטיין", image: PLACES.dachstein.image, url: PLACES.dachstein.web },
      { title: "רמסאו", image: PLACES.waldrand.image, url: PLACES.waldrand.web },
      { title: "הרים ואגמים", image: PLACES.reiteralm.image, url: PLACES.reiteralm.web },
      { title: "וינה", image: PLACES.vienna.image, url: PLACES.vienna.web },
    ],
    dates: "02.08 – 12.08.2026",
    tripCore: "03.08 – 11.08 באזור רמסאו",
    family: "זוג + 4 ילדים (6–14) + תינוקת בעגלה",
    card: "Schladming-Dachstein Card",
    cardNote: "תקף 14.05–01.11.2026 · פעיל מ-13:00 ביום ההגעה",
    kosher: true,
    shabbat: true,
    stroller: true,
    foodNote: "אוכל מהבית בלבד — פיקניק בכל יום, בלי מסעדות",
    principles: [
      "אין מוזיאונים / אין פארקי מים",
      "טבע, הרים, אגמים, רכבלים ומסלולים קלים",
      "שבת 08.08 — בלי רכב ובלי רכבלים",
      "אטרקציות יקרות רק אם באמת שוות",
    ],
  },

  flights: {
    outbound: {
      date: "02.08.2026 (ראשון)",
      depart: "17:30",
      from: "נתב\"ג",
      to: "וינה VIE",
      flight: "⬜ מספר טיסה",
      arrive: "~20:30–21:00 (משוער)",
      note: "איסוף רכב Europcar בשדה. לינה: Duplex Apartment",
    },
    inbound: [
      {
        id: "group-a",
        label: "קבוצה א' — 2 נוסעים",
        date: "11.08.2026 (שלישי)",
        depart: "21:35",
        from: "וינה VIE",
        to: "נתב\"ג",
        flight: "⬜ מספר טיסה",
        note: "הגעה לשדה ~18:30–19:00 (לפני 21:35). Wörschachklamm — מבוטל ביום זה",
      },
      {
        id: "group-b",
        label: "קבוצה ב' — שאר המשפחה",
        date: "12.08.2026 (רביעי)",
        depart: "10:30",
        from: "וינה VIE",
        to: "נתב\"ג",
        flight: "⬜ מספר טיסה",
        note: "לינה 11.08 ב-NH. החזרת רכב Europcar בבוקר + טיסה 10:30",
      },
    ],
    note: "רכב Europcar: איסוף 02.08 בשדה, החזרה 12.08 בבוקר. פיצול טיסות ב-11.08",
  },

  accommodations: [
    {
      id: "vienna-first",
      name: "Luxuriöses Duplex Apartment 130m²",
      address: "Heinestraße 19, 1020 Wien (רובע Leopoldstadt)",
      maps: "https://maps.google.com/?q=Heinestraße+19+1020+Wien",
      bookingUrl: "https://www.booking.com/Share-4DrwRU",
      checkIn: "02.08.2026",
      checkOut: "03.08.2026",
      nights: 1,
      type: "דירת דופלקס 130מ\"ר — 3 חדרי שינה, מטבח מלא",
      highlights: [
        "10 דק' הליכה מ-Praterstern (רכבת/רכבת תחתית)",
        "1.1 ק\"מ מהפרטר — נוח לילדים",
        "מטבח מלא — קניות השלמה לפני היציאה דרומה",
        "Shefa Market / סופרים עם Kosher Europe",
      ],
      confirmations: [
        { label: "הזמנה", value: "Booking.com" },
        { label: "צ'ק-אין", value: "⬜ שעה מהאישור" },
        { label: "סכום ששולם", value: "⬜ €" },
      ],
      contact: [],
      tips: [
        "מגיעים בערב — איסוף רכב Europcar בשדה אחרי הנחיתה",
        "מחר (03.08) בוקר רגוע: קניות בסופר, לא לחפוז!",
      ],
    },
    {
      id: "waldrand",
      name: "Waldrand Apartments — by myNests",
      address: "Vorberg 11, 8972 Ramsau am Dachstein",
      maps: "https://maps.google.com/?q=Vorberg+11+Ramsau+am+Dachstein",
      bookingUrl: "https://www.booking.com/Share-9zdOQc",
      website: "https://waldrand.rocks",
      checkIn: "03.08.2026",
      checkOut: "11.08.2026",
      nights: 8,
      type: "דירות עם מטבח — מארח משתתף ב-Schladming-Dachstein Card",
      highlights: [
        "Card פעיל מ-13:00 ביום ההגעה (03.08)",
        "שקט על שפת היער — ליד מסלולי טבע",
        "מטבח מלא — כל הארוחות מהבית",
        "שבת 08.08 — נשארים בדירה בלבד",
      ],
      confirmations: [
        { label: "הזמנה", value: "Booking.com — 03.08–11.08" },
        { label: "שעת צ'ק-אין", value: "⬜ מהאישור" },
        { label: "סכום ששולם", value: "⬜ €" },
        { label: "WiFi / קוד", value: "⬜ מהאישור" },
      ],
      contact: [
        { label: "טלפון", value: "+43 664 88232362", tel: true },
        { label: "אימייל", value: "office@waldrand.rocks" },
      ],
      tips: [
        "מגנט לחיישני מקרר (שבת)",
        "פלטה + שעון שבת",
        "כביסה — לתכנן לפני שבת 08.08",
      ],
    },
    {
      id: "vienna-airport",
      name: "NH Vienna Airport Conference Center",
      address: "Einfahrtsstraße 1-3, 1300 Schwechat (מול שדה התעופה)",
      maps: "https://maps.google.com/?q=NH+Vienna+Airport+Conference+Center",
      bookingUrl: "https://www.booking.com/Share-qZEbAi",
      checkIn: "11.08.2026 מ-15:00",
      checkOut: "12.08.2026 עד 12:00",
      nights: 1,
      type: "מלון 4 כוכבים — ממש ליד הטרמינל",
      highlights: [
        "הליכה / שאטל קצר לשדה — מושלם לטיסת בוקר",
        "לקבוצה ב' (טיסה 12.08 10:30)",
        "קבוצה א' (טיסה 11.08 21:35) — כנראה ישר לשדה בלי לינה",
      ],
      confirmations: [
        { label: "הזמנה", value: "Booking.com" },
        { label: "חניה", value: "~€42 ליום (אם צריך)" },
        { label: "סכום ששולם", value: "⬜ €" },
      ],
      contact: [
        { label: "טלפון", value: "+43 1 701510", tel: true },
      ],
      tips: [
        "צ'ק-אין מ-15:00 — ב-11.08 להגיע אחרי Wörschachklamm",
        "טיסה 10:30 ב-12.08 → לקום מוקדם, 3 שעות לפני טיסה",
        "16 דק' ברכבת למרכז וינה אם צריך",
      ],
    },
  ],

  bookings: [
    {
      id: "dachstein",
      priority: "critical",
      when: "מהבית — לפני הטיסה!",
      what: "רכבל Dachstein Glacier — 05.08",
      how: "derdachstein.at/reservierung",
      url: "https://www.derdachstein.at/reservierung",
      note: "חובה! בלי הזמנה אין עלייה. לבדוק שעה ביום הטיול",
      cost: "חינם בכרטיס (עם הזמנה)",
    },
    {
      id: "vignette",
      priority: "critical",
      when: "לפני כניסה לאוסטריה",
      what: "מדבקת כביש (Vignette) — 10 ימים",
      how: "asfinag.at או תחנת דלק",
      url: "https://shop.asfinag.at/en/buy-vignette/",
      note: "חובה לכבישים מהירים. שמרו אישור רכישה",
      cost: "~11.50€",
    },
    {
      id: "transfer",
      priority: "critical",
      when: "לפני הטיסה",
      what: "הסעה לשדה / מהשדה",
      how: "⬜ להזמין",
      url: "",
      note: "גם בחזרה 12.08",
      cost: "⬜ €",
    },
    {
      id: "hallstatt-mine",
      priority: "optional",
      when: "רק אם מחליטים ב-07.08",
      what: "מכרה מלח Hallstatt (אופציה יקרה)",
      how: "hallstatt.net / salzwelten.at",
      url: "https://www.hallstatt.net",
      note: "€49 מבוגר / €23 ילד. לא ברירת מחדל — Gosausee חינם",
      cost: "~200€+ משפחה",
    },
    {
      id: "intl-license",
      priority: "critical",
      when: "לפני הטיסה",
      what: "רישיון נהיגה בינלאומי — לשניכם",
      how: "רשות הרישוי / AAA",
      url: "",
      note: "גם רישיון ישראלי בתיק",
      cost: "⬜ ₪",
    },
  ],

  dontForget: [
    { id: "vomit-bags", text: "שקיות הקאה בתיק גב", cat: "נסיעה" },
    { id: "magnet", text: "מגנט לחיישני מקרר (שבת)", cat: "שבת" },
    { id: "euro-cash", text: "כסף יורו במזומן", cat: "כסף" },
    { id: "intl-license", text: "רישיון נהיגה בינלאומי — אליהו ואסתי", cat: "מסמכים" },
    { id: "israel-license", text: "רישיון נהיגה ישראלי — שניכם", cat: "מסמכים" },
    { id: "credit-cards", text: "אשראי על שם אליהו ואסתי (בלי עמלות המרה)", cat: "כסף" },
    { id: "bandages", text: "פלסטרים", cat: "בריאות" },
    { id: "meds", text: "תרופות אישיות", cat: "בריאות" },
    { id: "sunscreen", text: "משחת שיזוף / קרם הגנה", cat: "בריאות" },
    { id: "mosquito", text: "רול נגד יתושים", cat: "בריאות" },
    { id: "eye-drops", text: "טיפות עיניים (אלרגיה)", cat: "בריאות" },
    { id: "hotplate", text: "פלטה חשמלית", cat: "שבת" },
    { id: "shabbat-clock", text: "שעון שבת", cat: "שבת" },
    { id: "laptop", text: "מחשב + מטען", cat: "אלקטרוניקה" },
    { id: "adapter", text: "מתאם לשקע אירופאי", cat: "אלקטרוניקה" },
    { id: "lamp", text: "מנורה נטענת", cat: "אלקטרוניקה" },
    { id: "chumash-siddur", text: "חומש, סידורים, דברים לשבת", cat: "שבת" },
    { id: "football", text: "כדורגל", cat: "בילוי" },
    { id: "shabbat-games", text: "משחקים לשבת", cat: "שבת" },
    { id: "tick-books", text: "ספרי נגד קרציות", cat: "בריאות" },
    { id: "shabbat-map", text: "מפה לשבת", cat: "שבת" },
    { id: "kiddush-cup", text: "גביע לקידוש", cat: "שבת" },
    { id: "cutlery", text: "סכום (כלי אוכל אמיתיים)", cat: "מטבח" },
    { id: "peeler", text: "מקלף", cat: "מטבח" },
    { id: "toaster", text: "טוסטר", cat: "מטבח" },
    { id: "grater", text: "מגרדת", cat: "מטבח" },
    { id: "hand-blender", text: "בלנדר יד", cat: "מטבח" },
    { id: "transfer", text: "לארגן הסעה לשדה", cat: "לוגיסטיקה" },
    { id: "kosher-app", text: "להוריד Kosher Europe לאפליקציה", cat: "כשרות" },
  ],

  shopping: [
    {
      id: "disposable",
      name: "חד\"פ",
      items: [
        "צלחות פשוטות", "מזלגות", "סכינים", "כפיות", "כפות", "כוסות",
        "חבילת כוסות אחת לשבת", "נייר כסף", "נילון לשולחן",
        "קופסאות לסלטים", "תבניות אלומניום", "שקיות אוכל",
        "קופסאות אחסון", "שקיות פח", "סמרטוטים",
      ],
    },
    {
      id: "meat",
      name: "בשרים",
      items: [
        "עופות", "חזה עוף (לשווארמה וליל שבת)", "אסאדו (חמישי, שבת לילה, שבת בוקר)",
        "שניצלים (3 ארוחות)", "פרגיות (במקום על האש)", "פסטרמות", "נקניקיות",
      ],
    },
    {
      id: "dry",
      name: "יבשים",
      items: [
        "מנות חמות", "שומשום", "גריסים", "שעועית", "קוסקוס (2 ארוחות)",
        "פתיתים", "אורז (2 ארוחות)", "פסטה", "ממרח שוקולד", "עיסה לעוגות",
        "שמרים", "קמח", "צ'ילי", "סויה", "סילאן", "שוקו", "קפה", "סוכרזית",
        "רוטב לעוף מוכן", "תבלין שווארמה", "כורכום", "תבלינים רגילים",
        "טחינה", "מלפפון חמוץ", "טונה", "רסק עגבניות", "קטשופ", "חרדל",
        "תוספות לסלטים (חמוציות, שקדים וכו')", "שמן", "מיץ לימון", "חומץ",
        "חטיפים", "ממתקים", "עוגיות", "ופלים", "שוגי",
      ],
    },
    {
      id: "veg",
      name: "ירקות",
      items: ["חסה", "פטרוזיליה", "כוסברה", "כרוב", "שום קלוף?"],
    },
    {
      id: "pdf-kitchen",
      name: "מטבח (מהצ'קליסט)",
      items: [
        "שקיות תבלינים", "שמרים בשקיקים", "אבקות מרק", "סכום חד\"פ",
        "סכין, מקל בלנדר, מחבתות", "קולפן", "כלי מטבח", "כוסות קמפינג",
        "נשנושים וממתקים", "אבקות להכנת עוגות",
      ],
    },
    {
      id: "pdf-kosher-shop",
      name: "השלמות כשרות (בוינה)",
      items: [
        "חלב", "גבינות", "גבינ\"צ", "קוטג'", "יוגורט", "מיץ ענבים",
        "לחמים / לחמניות / פיתות", "ביצים", "דגני בוקר",
      ],
    },
  ],

  preTripChecklist: [
    {
      id: "docs",
      name: "מסמכים והכנות",
      items: [
        "דרכונים", "רישיון נהיגה + בינלאומי", "ביטוח — להדפיס",
        "כרטיסי טיסה", "צילום דרכון / עותק דיגיטלי",
        "כרטיס אשראי ללא עמלות המרה", "להגדיל מסגרת אשראי",
        "מט\"ח (יורו)", "סים לטלפונים", "מפות Google אופליין",
      ],
    },
    {
      id: "toiletries",
      name: "תיק רחצה",
      items: [
        "שמפו / סבון / ספוג", "דאודורנט / בושם", "מברשת + משחת שיניים",
        "מגבונים לחים / טישיו", "קסמי שיניים", "שפתון ליובש",
        "קרם הגנה", "רול נגד יתושים",
      ],
    },
    {
      id: "clothes",
      name: "בגדים",
      items: [
        "חולצות שרוול ארוך + קצר", "מכנסיים קצר + ארוך", "תחתונים / גופיות",
        "גרביים", "פיג'מה", "בגד ים", "קפוצ'ון / ג'קט", "מעיל גשם דק",
        "נעליים + נעליים לשבת", "נעלי טרק", "מסרק", "ספרי קריאה",
      ],
    },
    {
      id: "shabbat-pack",
      name: "לשבת",
      items: [
        "ציצית", "סידור", "טלית ותפילין", "נרות לשבת", "מצית",
        "פלטה חשמלית מתגלגלת", "מגנט לחיישני מקרר",
        "חגורת דומי למפתח שבת", "שעון שבת", "מסקינג טייפ לתאורה", "כובע",
        "מפה לשבת", "גביע לקידוש",
      ],
    },
    {
      id: "health",
      name: "בריאות",
      items: [
        "תרופות אישיות", "אקמול / אדויל", "פלסטרים", "פניסטיל",
        "כדורים נגד בחילות", "טיפות עיניים", "ספרי נגד קרציות",
      ],
    },
    {
      id: "plane",
      name: "למטוס",
      items: [
        "כרית לצוואר", "כיסוי עיניים", "מסטיקים", "אוכל לנשנוש",
        "שקיות הקאה", "בקבוקים / חיתולים לתינוקת",
      ],
    },
    {
      id: "outdoor",
      name: "טיולים ושטח (ברכב)",
      items: [
        "תיק גב", "סנדלים למים", "משקפי שחייה", "כובע שמש",
        "שנורקל / בקבוק מים", "פק\"ל קפה", "צידנית",
        "בגדי ים", "מגבות", "שמיכות דקות", "סוללה נטענת", "קרם הגנה",
      ],
    },
    {
      id: "electronics",
      name: "אלקטרוניקה",
      items: [
        "טלפון + מטען", "מחשב + מטען", "סוללה נטענת + מטען",
        "מתאם לשקע אירופאי", "שעון שבת", "פנס", "בלנדר יד",
        "מצלמה + מטען", "אוזניות",
      ],
    },
    {
      id: "before-leave",
      name: "לפני יציאה מהבית",
      items: [
        "להשאיר מפתח לדואר", "לבדוק משקל מזוודות",
        "כיבוי אורות + שעון שבת", "לבדוק גז וחשמל מכובים",
      ],
    },
  ],

  cardCoverage: [
    { name: "Schladming-Dachstein Card", status: "כלול", note: "מ-13:00 ביום הגעה", url: PLACES.schladmingCard.web },
    { name: "Planai + Hopsiland", status: "כלול", note: "יום משפחתי מעולה", url: PLACES.planai.web },
    { name: "Dachstein Glacier", status: "כלול", note: "הזמנה חובה!", url: PLACES.dachstein.web, book: PLACES.dachstein.book },
    { name: "Reiteralm + Stroller Trail", status: "כלול", note: "הכי נוח לעגלה", url: PLACES.reiteralm.web },
    { name: "Rittisberg", status: "כלול", note: "יום רך אחרי שבת", url: PLACES.rittisberg.web },
    { name: "Hauser Kaibling", status: "כלול", note: "ברירת מחדל 10.08", url: PLACES.hauserKaibling.web },
    { name: "Hochwurzen", status: "כלול", note: "חלופה ל-10.08", url: PLACES.hochwurzen.web },
    { name: "Wörschachklamm", status: "כלול", note: "אפשר ביום 10.08", url: PLACES.woerschachklamm.web },
    { name: "Wilder Berg Mautern", status: "כלול", note: "מ-13:00 ביום הגעה", url: PLACES.wildeBerg.web },
    { name: "Hallstatt Salt Mine", status: "לא כלול", note: "€49 / €23 — אופציה", url: PLACES.hallstattMine.web, book: PLACES.hallstattMine.book },
    { name: "Gosausee", status: "חינם", note: "תוספת ליד הלשטאט", url: PLACES.gosausee.web },
    { name: "Coaster / Flyline / GoKarts", status: "לא כלול", note: "רק אם מתחשק", url: PLACES.rittisberg.web },
  ],

  days: [
    {
      id: "day0",
      date: "02.08",
      weekday: "ראשון",
      title: "וינה — לילה ראשון",
      emoji: "✈️",
      placeKey: "vienna",
      summary: "טיסה 17:30 → Duplex Apartment → קניות כשרות",
      activities: [
        { time: "17:30", name: "המראה מנתב\"ג", price: "", notes: "⬜ מספר טיסה" },
        { time: "~20:30", name: "נחיתה בוינה VIE", price: "", notes: "דלק מלא? בדקו באיסוף", url: PLACES.viennaAirport.web, maps: PLACES.viennaAirport.maps },
        { time: "~21:00", name: "איסוף רכב Europcar בשדה", price: "", notes: "", url: PLACES.europcar.book, book: PLACES.europcar.book },
        { time: "21:30", name: "צ'ק-אין: Duplex Apartment", price: "", notes: "Heinestraße 19, 130מ\"ר", maps: "https://maps.google.com/?q=Heinestraße+19+1020+Wien" },
        { time: "ערב", name: "קניות השלמה (אם יש כוח)", price: "⬜ €", notes: "או מחר בבוקר — Shefa / Kosher Europe", maps: PLACES.shefa.maps },
      ],
      totalEstimate: "קניות לפי צורך",
      dailyChecklist: ["מים", "חיתולים", "אוכל לדרך למחר"],
    },
    {
      id: "day1",
      date: "03.08",
      weekday: "שני",
      title: "וינה: קניות + יציאה דרומה",
      emoji: "🛒",
      placeKey: "vienna",
      summary: "בוקר רגוע — סופר, ארוחת בוקר, פיקניק בדרך",
      activities: [
        { time: "08:00", name: "ארוחת בוקר בדירה", price: "", notes: "אורז מהבית — בלי לחפוז" },
        { time: "09:00", name: "קניות בסופר בוינה", price: "⬜ €", notes: "חלב, גבינות, ירקות, השלמות", maps: PLACES.shefa.maps, url: PLACES.vienna.web },
        { time: "11:00", name: "יציאה מוינה דרומה", price: "", notes: "רק אחרי הקניות!", book: PLACES.asfinag.book },
        { time: "12:30", name: "פיקניק בדרך", price: "חינם", notes: "אורז / מה שבישלתם" },
        { time: "13:00", name: "אופציה: Der Wilde Berg Mautern", price: "חינם בכרטיס", notes: "מ-13:00 בלבד", url: PLACES.wildeBerg.web, maps: PLACES.wildeBerg.maps },
        { time: "17:00", name: "צ'ק-אין Waldrand Apartments", price: "", notes: "Vorberg 11", url: PLACES.waldrand.web, maps: PLACES.waldrand.maps },
      ],
      totalEstimate: "קניות + דלק",
      weatherTip: "היום הכי חשוב לקניות — לא לדחוס בבוקר!",
      dailyChecklist: ["רשימת קניות", "צידנית", "אורז/אוכל לפיקניק", "כרטיס Card"],
    },
    {
      id: "day2",
      date: "04.08",
      weekday: "שלישי",
      title: "Planai + Hopsiland",
      emoji: "🎠",
      placeKey: "planai",
      summary: "יום פתיחה מושלם לילדים — משחקים על ההר",
      activities: [
        { time: "09:15", name: "רכבל Planai", price: "חינם בכרטיס", notes: "עלייה + ירידה", url: PLACES.planai.web, maps: PLACES.planai.maps },
        { time: "09:45", name: "Hopsiland — מסלול משחקים", price: "חינם בכרטיס", notes: "איזון, קפיצות, מגלשות", url: PLACES.planai.web },
        { time: "12:45", name: "פיקניק ליד תחנת העלייה", price: "", notes: "אוכל מהבית" },
        { time: "13:30", name: "ירידה וחזרה ל-Waldrand", price: "", notes: "אחה\"צ חופשי", maps: PLACES.waldrand.maps },
      ],
      totalEstimate: "0€",
      dailyChecklist: ["כובעים", "קרם הגנה", "מים", "שכבות"],
    },
    {
      id: "day3",
      date: "05.08",
      weekday: "רביעי",
      title: "Dachstein Glacier — היום המיוחד!",
      emoji: "❄️",
      placeKey: "dachstein",
      summary: "קרחון, תצפיות, קור באוגוסט",
      activities: [
        { time: "08:15", name: "נסיעה לתחנת Dachstein", price: "", notes: "לבדוק שעת ההזמנה!", maps: PLACES.dachstein.maps },
        { time: "09:30", name: "רכבל Dachstein Glacier", price: "חינם + הזמנה חובה", notes: "אישור הזמנה ביד!", url: PLACES.dachstein.web, book: PLACES.dachstein.book },
        { time: "10:00", name: "תצפיות Sky Walk / Ice Palace", price: "בסיס חינם", notes: "תוספות בתשלום. מעילים!", url: PLACES.dachstein.web },
        { time: "13:30", name: "ירידה + פיקניק + מנוחה", price: "", notes: "לא לדחוס עוד פעילות היום" },
      ],
      totalEstimate: "0€ (בסיס) / תוספות אופציונליות",
      weatherTip: "רוח וקור גם בקיץ — שכבות לכולם",
      dailyChecklist: ["אישור הזמנה דכשטיין", "מעילים", "מנשא לתינוקת", "לא עגלה"],
    },
    {
      id: "day4",
      date: "06.08",
      weekday: "חמישי",
      title: "Reiteralm — שביל עגלה",
      emoji: "🚡",
      placeKey: "reiteralm",
      summary: "היום הכי נוח לעגלה — Stroller Trail",
      activities: [
        { time: "09:30", name: "Preunegg Jet", price: "חינם בכרטיס", notes: "", url: PLACES.reiteralm.web, maps: PLACES.reiteralm.maps },
        { time: "10:00", name: "Stroller Trail Reiteralm", price: "חינם", notes: "1.6 ק\"מ, ~40 דק'", url: PLACES.reiteralm.web },
        { time: "12:30", name: "פיקניק ליד Reiteralmsee", price: "", notes: "" },
        { time: "13:30", name: "ירידה וחזרה לדירה", price: "", notes: "", maps: PLACES.waldrand.maps },
      ],
      totalEstimate: "0€",
      dailyChecklist: ["עגלה", "מצלמה", "אוכל לפיקניק"],
    },
    {
      id: "day5",
      date: "07.08",
      weekday: "שישי",
      title: "Hallstatt",
      emoji: "🏔️",
      placeKey: "hallstatt",
      summary: "הכפר על האגם — אופציונלי: מכרה מלח",
      activities: [
        { time: "08:00", name: "יציאה מוקדמת להלשטאט", price: "חניה ~10€", notes: "לפני 10:00!", maps: PLACES.hallstatt.maps },
        { time: "09:30", name: "סיור בכפר + טיילת", price: "חינם", notes: "החלק היפה בלי לשלם", url: PLACES.hallstatt.web },
        { time: "12:00", name: "פיקניק", price: "", notes: "אוכל מהבית" },
        { time: "13:00", name: "אופציה: מכרה מלח Hallstatt", price: "€49 / €23", notes: "או Gosausee בחינם", url: PLACES.hallstattMine.web, book: PLACES.hallstattMine.book },
        { time: "אחה\"צ", name: "אופציה: אגם Gosausee", price: "חינם", notes: "אם מדלגים על המכרה", url: PLACES.gosausee.web, maps: PLACES.gosausee.maps },
      ],
      totalEstimate: "10€ חניה (+ מכרה אם בוחרים)",
      weatherTip: "Gosausee = תוספת טבע חינמית",
      swap: "מכרה רק אם באמת שווה — לא ברירת מחדל",
    },
    {
      id: "day6",
      date: "08.08",
      weekday: "שבת",
      title: "שבת בדירה",
      emoji: "🕯️",
      placeKey: "waldrand",
      summary: "בלי רכב, בלי רכבלים — מנוחה מלאה",
      activities: [
        { time: "כל היום", name: "סעודות, משחקים, הליכה קצרה ליד הדירה", price: "0€", notes: "כביסה, מנוחה, התארגנות לשבוע הבא" },
      ],
      totalEstimate: "0€",
      dailyChecklist: ["נרות", "פלטה", "חמין", "שעון שבת"],
    },
    {
      id: "day7",
      date: "09.08",
      weekday: "ראשון",
      title: "Rittisberg",
      emoji: "🌲",
      placeKey: "rittisberg",
      summary: "יום רך אחרי שבת — טבע ומשפחתיות",
      activities: [
        { time: "09:45", name: "הגעה ל-Rittisberg", price: "חינם בכרטיס", notes: "קרוב לדירה", url: PLACES.rittisberg.web, maps: PLACES.rittisberg.maps },
        { time: "10:15", name: "Nature Adventure Trail", price: "חינם", notes: "מסלול משפחתי רגוע", url: PLACES.rittisberg.web },
        { time: "12:45", name: "פיקניק", price: "", notes: "" },
        { time: "13:30", name: "חזרה לדירה", price: "", notes: "Coaster/Flyline בתשלום", url: PLACES.rittisberg.web },
      ],
      totalEstimate: "0€",
    },
    {
      id: "day8",
      date: "10.08",
      weekday: "שני",
      title: "Hauser Kaibling (או Hochwurzen)",
      emoji: "🐑",
      placeKey: "hauserKaibling",
      summary: "ברירת מחדל: הר משפחתי עם כבשים",
      activities: [
        { time: "09:30", name: "רכבל Hauser Kaibling", price: "חינם בכרטיס", notes: "ברירת מחדל", url: PLACES.hauserKaibling.web, maps: PLACES.hauserKaibling.maps },
        { time: "10:00", name: "מסלול משפחתי + כבשים", price: "חינם", notes: "", url: PLACES.hauserKaibling.web },
        { time: "אופציה", name: "חלופה: Hochwurzen + Bankerlweg", price: "חינם בכרטיס", notes: "יום רגוע יותר", url: PLACES.hochwurzen.web, maps: PLACES.hochwurzen.maps },
        { time: "אופציה", name: "Wörschachklamm (אם יש כוח)", price: "חינם בכרטיס", notes: "הועבר מ-11.08", url: PLACES.woerschachklamm.web, maps: PLACES.woerschachklamm.maps },
        { time: "12:30", name: "פיקניק", price: "", notes: "" },
        { time: "13:15", name: "חזרה לדירה", price: "", notes: "", maps: PLACES.waldrand.maps },
      ],
      totalEstimate: "0€",
      weatherTip: "Hochwurzen = יום רגוע יותר אם עייפים",
    },
    {
      id: "day9",
      date: "11.08",
      weekday: "שלישי",
      title: "יום נסיעה לשדה + טיסת ערב",
      emoji: "✈️",
      placeKey: "viennaAirport",
      summary: "יציאה מוקדמת — הגעה לשדה ~19:00",
      activities: [
        { time: "07:30", name: "צ'ק-אאוט Waldrand", price: "", notes: "ארוחת בוקר מהבית", maps: PLACES.waldrand.maps },
        { time: "09:00", name: "יציאה מרמסאו לשדה", price: "", notes: "~3 שעות נסיעה", maps: PLACES.viennaAirport.maps },
        { time: "11:30", name: "פיקניק / מנוחה בדרך", price: "", notes: "" },
        { time: "12:30", name: "הגעה לאזור שדה / NH Airport", price: "", notes: "מנוחה לפני הטיסה", url: "https://www.nh-hotels.com/en/hotel/nh-vienna-airport-conference-center", maps: PLACES.viennaAirport.maps },
        { time: "18:30", name: "הגעה לטרמינל — קבוצה א'", price: "", notes: "בשדה עד 19:00", url: PLACES.viennaAirport.web },
        { time: "21:35", name: "🛫 המראה — קבוצה א'", price: "", notes: "⬜ מספר טיסה" },
      ],
      totalEstimate: "דלק",
      dailyChecklist: ["לארוז הכל", "תדלוק לפני שדה?", "תיק יד לטיסת ערב"],
      weatherTip: "עדיפות: להגיע לשדה רגועים ~19:00",
      swap: "Wörschachklamm הועבר — אין זמן ביום טיסת ערב",
    },
    {
      id: "day10",
      date: "12.08",
      weekday: "רביעי",
      title: "טיסה הביתה — קבוצה ב'",
      emoji: "🏠",
      placeKey: "viennaAirport",
      summary: "NH Airport → שדה → המראה 10:30",
      activities: [
        { time: "07:00", name: "צ'ק-אאוט NH Vienna Airport", price: "", notes: "עד 12:00", url: "https://www.nh-hotels.com/en/hotel/nh-vienna-airport-conference-center" },
        { time: "07:00", name: "החזרת רכב Europcar + תדלוק", price: "", notes: "+30 דק'", url: PLACES.europcar.book, maps: PLACES.viennaAirport.maps },
        { time: "07:30", name: "צ'ק-אין — שאר המשפחה", price: "", notes: "3 שעות לפני!", url: PLACES.viennaAirport.web },
        { time: "10:30", name: "🛫 המראה — קבוצה ב'", price: "", notes: "⬜ מספר טיסה" },
      ],
      totalEstimate: "",
    },
  ],

  car: {
    rental: {
      company: "Europcar",
      pickup: "02.08.2026 ~21:00 — נמל תעופה וינה (VIE)",
      return: "12.08.2026 בבוקר — נמל תעופה וינה (VIE)",
      url: "https://www.europcar.com",
      note: "איסוף אחרי הנחיתה בערב. החזרה בבוקר רביעי לפני טיסה 10:30",
      checklist: [
        "רישיון ישראלי + בינלאומי (שניכם)",
        "כרטיס אשראי על שם ההזמנה",
        "צלם/תעד נזקים קיימים באיסוף",
        "בדקו: מושב תינוק, GPS, שרשרת שלג?",
        "Vignette לפני כניסה לכביש מהיר",
        "תדלוק מלא לפני החזרה",
      ],
    },
    vignette: {
      title: "אגרת כביש (Vignette)",
      required: true,
      description: "חובה לכבישים מהירים באוסטריה",
      where: [
        { place: "אונליין", how: "asfinag.at", url: "https://www.asfinag.at" },
        { place: "תחנות דלק / טבק", how: "OMV, Shell, Trafik" },
      ],
      types: [{ name: "10 ימים", price: "~11.50€", note: "מתאים לטיול" }],
      tips: ["דיגיטלית לפי מספר רכב — שמרו אישור"],
    },
    rentalDetails: [
      { label: "חברה", value: "Europcar" },
      { label: "איסוף", value: "02.08 ~21:00, שדה וינה" },
      { label: "החזרה", value: "12.08 בבוקר, שדה וינה" },
      { label: "מספר הזמנה", value: "⬜ להוסיף" },
      { label: "סכום ששולם", value: "⬜ €" },
    ],
  },

  kosher: {
    apps: [
      {
        name: "Kosher Europe",
        desc: "האפליקציה שהמליצו — סריקת מוצרים כשרים באירופה",
        platforms: "iOS + Android",
        ios: "https://apps.apple.com/app/kosher-europe/id6758014012",
        android: "https://play.google.com/store/apps/details?id=at.itbh.ke.app",
      },
      {
        name: "Is It Kosher?",
        desc: "סריקת ברקוד נוספת",
        platforms: "iOS / Android",
      },
    ],
    vienna: [
      { name: "Shefa Market", note: "מכולת כשרה מלאה" },
      { name: "Spar / Billa / Hofer", note: "מוצרים ארוזים עם חותם OU/OK" },
    ],
    tips: [
      "כל הארוחות מהבית — אין מסעדות בתוכנית",
      "בוינה (02.08): קניות השלמה לפני היציאה דרומה",
      "חלב, גבינות, לחם — בוינה בלבד",
      "שבת: פלטה, חמין, הכנה ביום ו' (07.08 בערב)",
    ],
    symbols: ["OU", "OK", "Kof-K", "Badatz"],
  },

  shabbat: {
    date: "08.08.2026",
    plan: "יום מנוחה מלא בדירה — בלי רכב ובלי רכבלים",
    prep: "יום שישי 07.08 בערב: בישול, חמין על פלטה, מקלחות, הכנות",
    items: ["נרות", "פלטה", "שעון שבת", "מגנט למקרר", "מפה", "גביע קידוש", "חומש וסידורים", "משחקים"],
  },

  dailyChecklistTemplate: [
    "מים", "כובעים", "קרם הגנה", "שכבות לבוש",
    "חיתולים / מגבונים", "אוכל לפיקניק",
    "כרטיס Card בטלפון", "מטען", "שקיות זבל",
    "נעלי הליכה", "מנשא / עגלה",
  ],

  budget: {
    categories: [
      { name: "Duplex Apartment וינה (02.08)", estimate: "⬜ €", paid: "⬜ €" },
      { name: "Waldrand Apartments (03–11.08)", estimate: "⬜ €", paid: "⬜ €" },
      { name: "NH Vienna Airport (11.08)", estimate: "⬜ €", paid: "⬜ €" },
      { name: "רכב Europcar (02–12.08)", estimate: "⬜ €", paid: "⬜ €" },
      { name: "Vignette", estimate: "~11.50€", paid: "⬜ €" },
      { name: "Schladming-Dachstein Card", estimate: "⬜ €", paid: "⬜ €" },
      { name: "טיסות", estimate: "⬜ €", paid: "⬜ €" },
      { name: "הסעות", estimate: "⬜ €", paid: "⬜ €" },
      { name: "חניה Hallstatt + אחר", estimate: "~10€", paid: "⬜ €" },
      { name: "קניות אוכל", estimate: "⬜ €", paid: "⬜ €" },
      { name: "אופציות (מכרה וכו')", estimate: "0–200€", paid: "⬜ €" },
    ],
  },

  emergency: [
    { label: "חירום אירופה", value: "112" },
    { label: "הצלה הרים", value: "140" },
    { label: "שגרירות ישראל וינה", value: "+43 1 476 666 0", tel: true },
  ],

  apps: [
    { name: "Kosher Europe", desc: "סריקת מוצרים כשרים — חובה!" },
    { name: "Schladming-Dachstein", desc: "כרטיס דיגיטלי + מפה" },
    { name: "bergfex", desc: "מזג אוויר הרים" },
    { name: "Google Maps", desc: "הורידי מפה אופליין!" },
    { name: "ASFiNAG", desc: "Vignette" },
  ],

  friendPlanNote: "יש גם תוכנית מפורטת של חבר (V4.2) עם אומגה, גו-קארט, פראטר וזלצבורגרלנד — לא בתוכנית שלנו, אבל אפשר לשאוב רעיונות.",
};
